export { default as Home } from "./home";
export { default as Browse } from "./browse";
export { default as Signin } from "./signin";
export { default as Signup } from "./signup";
export { default as Search } from "./search";
export { default as Watch } from "./watch";
export { default as Trending } from "./trending";
export { default as Movies } from "./movies";
export { default as Series } from "./series";
